#define WIFI_SSID "SSID"
#define WIFI_PASS "PASSWORD"
#define API_KEY ""
#define City_ID "146268"
#define API_HOST "api.openweathermap.org"
#define API_APRS ""
#define API_APRS_HOST "api.aprs.fi"
#define API_APRS_CALLSIGN "N0CALL"
#define API_APRS_PASSCODE "12345"
#define Solar_Panel_IP ""
#define Fireserver_IP ""
#define LATITUDE_""
#define LONGITUDE_ ""
#define BB_COMMENT_""